Disable doctests until they work without editable installs
When doing a non-editable install of cocotb, the tests fail with:

```
ERROR cocotb/utils.py - ImportError: cannot import name 'simulator' from partially initialized module 'cocotb' (most likely due to a circular import) (/home/runner/work/cocotb/cocotb/cocotb/__init__.py)
ERROR cocotb/utils.py
ERROR cocotb/binary.py - ImportError: cannot import name 'simulator' from partially initialized module 'cocotb' (most likely due to a circular import) (/home/runner/work/cocotb/cocotb/cocotb/__init__.py)
ERROR cocotb/binary.py
ERROR cocotb/types/__init__.py - ImportError: cannot import name 'simulator' from partially initialized module 'cocotb' (most likely due to a circular import) (/home/runner/work/cocotb/cocotb/cocotb/__init__.py)
ERROR cocotb/types/array.py - ImportError: cannot import name 'simulator' from partially initialized module 'cocotb' (most likely due to a circular import) (/home/runner/work/cocotb/cocotb/cocotb/__init__.py)
ERROR cocotb/types/logic.py - ImportError: cannot import name 'simulator' from partially initialized module 'cocotb' (most likely due to a circular import) (/home/runner/work/cocotb/cocotb/cocotb/__init__.py)
ERROR cocotb/types/logic_array.py - ImportError: cannot import name 'simulator' from partially initialized module 'cocotb' (most likely due to a circular import) (/home/runner/work/cocotb/cocotb/cocotb/__init__.py)
ERROR cocotb/types/range.py - ImportError: cannot import name 'simulator' from partially initialized module 'cocotb' (most likely due to a circular import) (/home/runner/work/cocotb/cocotb/cocotb/__init__.py)
ERROR cocotb/_sim_versions.py - ImportError: cannot import name 'simulator' from partially initialized module 'cocotb' (most likely due to a circular import) (/home/runner/work/cocotb/cocotb/cocotb/__init__.py)
ERROR cocotb/_sim_versions.py
```

Disable them until we have figured out what's going on.