CI: Disable ccache for self-hosted builds
Riviera-PRO sets LD_LIBRARY_PATH to include a libstdc++ build that
breaks compiling cocotb with ccache.

```
  g++ -Werror -Wno-error=deprecated-declarations -Wsuggest-override -Og -g --coverage -fPIC -DGPILOG_EXPORTS= -D__STDC_FORMAT_MACROS= -Isrc/cocotb/share/include -Isrc/cocotb -I/opt/actions-runner/_work/cocotb/cocotb/.nox/dev_test_sim-sim-riviera-toplevel_lang-vhdl-gpi_interface-vhpi/include -I/opt/actions-runner/_work/_tool/Python/3.9.23/x64/include/python3.9 -c src/cocotb/share/lib/gpi_log/gpi_logging.cpp -o build/temp.linux-x86_64-cpython-39/cocotb/libs/libgpilog/src/cocotb/share/lib/gpi_log/gpi_logging.o -std=c++11 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Wcast-qual -Wwrite-strings -Wconversion -Wno-missing-field-initializers -Werror=shadow -Wnon-virtual-dtor -Woverloaded-virtual -flto
  /usr/lib/ccache/g++: /nas/fossif/tools/aldec/rivierapro/2022.04/linux64/bin/Linux64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/ccache/g++)
  error: command '/usr/lib/ccache/g++' failed with exit code 1
```

Disable ccache on self-hosted builds for now.