Fix RegressionManager startup in Python 3.11
Python 3.11 reports:

```
   Traceback (most recent call last):
    File "/home/runner/work/cocotb/cocotb/cocotb/__init__.py", line 262, in _initialise_testbench
      _initialise_testbench_(argv_)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/cocotb/cocotb/cocotb/__init__.py", line 370, in _initialise_testbench_
      regression_manager = RegressionManager.from_discovery(top)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/cocotb/cocotb/cocotb/regression.py", line 152, in from_discovery
      return cls(dut, tests)
             ^^^^^^^^^^^^^^^
    File "/home/runner/work/cocotb/cocotb/cocotb/regression.py", line 139, in __init__
      self._queue.sort(key=lambda test: (test.stage, test._id))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

This issue is due to a change in Python 3.11:

> When sorting using tuples as keys, the order of the result may differ
> from earlier releases if the tuple elements don’t define a total
> ordering (see Value comparisons for information on total ordering). It’s
> generally true that the result of sorting simply isn’t well-defined in
> the absence of a total ordering on list elements.
-- https://docs.python.org/3.11/whatsnew/3.11.html#changes-in-the-python-api

`test.stage` is nullable and leads to tuples like `(None, 2)` being
sorted.

This fix makes `test.stage` 0 by default instead of None as before. This
is strictly an API change, but seems innocent enough to just go with it.