Make test_deprecated work with pytest 8
Pytest 8 introduced new behavior for `pytest.warn()`, which isn't
compatible with our code in `test_unicode_handle_assignment_deprecated`.
Update the test to be skipped entirely for Icarus and GHDL instead of
testing for specific exceptions. (The test doesn't do anything on these
simulators anyways.)

See also https://github.com/pytest-dev/pytest/pull/11129

Error message, as seen in CI:
```

     1.00ns INFO     cocotb.regression                  running test_unicode_handle_assignment_deprecated (2/195)
     1.00ns INFO     cocotb.regression                  test_unicode_handle_assignment_deprecated failed: errored with unexpected type
  Traceback (most recent call last):
    File "/home/runner/work/cocotb/cocotb/tests/test_cases/test_cocotb/test_deprecated.py", line 39, in test_unicode_handle_assignment_deprecated
      dut.stream_in_string.value = "Bad idea"
    File "/home/runner/work/cocotb/cocotb/.nox/dev_test_sim-sim-icarus-toplevel_lang-verilog-gpi_interface-vpi/lib/python3.8/site-packages/cocotb/handle.py", line 370, in __getattr__
      raise AttributeError(f"{self._name} contains no object named {name}")
  AttributeError: sample_module contains no object named stream_in_string

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/runner/work/cocotb/cocotb/tests/test_cases/test_cocotb/test_deprecated.py", line 39, in test_unicode_handle_assignment_deprecated
      dut.stream_in_string.value = "Bad idea"
    File "/home/runner/work/cocotb/cocotb/.nox/dev_test_sim-sim-icarus-toplevel_lang-verilog-gpi_interface-vpi/lib/python3.8/site-packages/_pytest/recwarn.py", line 322, in __exit__
      fail(
    File "/home/runner/work/cocotb/cocotb/.nox/dev_test_sim-sim-icarus-toplevel_lang-verilog-gpi_interface-vpi/lib/python3.8/site-packages/_pytest/outcomes.py", line 166, in fail
      raise Failed(msg=reason, pytrace=pytrace)
  Failed: DID NOT WARN. No warnings of type (<class 'DeprecationWarning'>,) were emitted.
    Emitted warnings: [].
```