Handle _sim_event() call when scheduler was not initialized
Fallback to cocotb.log.error() when there is no scheduler object.
Before this change, scheduler.log.error() would cause the following AttributeError:

Traceback (most recent call last):
  File <...>/cocotb/__init__.py, line 309, in _sim_event
    scheduler.log.error(msg)
AttributeError: 'NoneType' object has no attribute 'log'

(cherry picked from commit 57405f2bb144a81f69f3bdb0a4e315e19026c737)