Fix LogicArray.reverse()
Failed example:
  File "logic_array.py" (doctest)
    la.reverse()
  File "logic_array.py", line 194, in reverse
    return type(self)(reversed(self), range=reversed(self.range))
  File "logic_array.py", line 184, in __init__
    if len(self._value) != len(self._range):
  Error:
    TypeError: object of type 'range_iterator' has no len()

Explanation:
Range.__reversed__() returns an range_iterator and LogicArray's constructor (LogicArray.__init__())
expects a Range.

Fix:
Implement a Range.reverse() function to return a reversed Range

Alternative:
Modify Range.__reversed__() to return a reversed Range instead of a
range_iterator