Remove `BinaryValue.get_hex_buff` which is nonsense (#1511)
This was introduced in 030a25bdeae4d02db12becf461f33c5d4217c67f with no explanation or docstring. Here is a sample of its behavior:
```
>>> BinaryValue('1111').get_hex_buff()
ValueError: invalid literal for int() with base 2: '\x0f'

# 0b00110001 is ascii 1
>>> BinaryValue('00110001').get_hex_buff()
'1'

>>> BinaryValue('00110001' + '00110000').get_hex_buff()
'2'
```

The semantics seem to be:
* Intepret the binary value as an ascii string
* ensure the only ascii characters are 0 and 1
* decode those ascii characters to a binary integer
* encode that binary integer as hex

Clearly this is nonsense. `BinaryValue.hex` produces much saner results.