fixed issue caused by ipython history opened in dead process
The following error occurs on a windows machine due to PID of the thread changing.
`File "C:\Users\mcheah\git\cocotb\env\lib\site-packages\IPython\core\history.py", line 812, in _writeout_input_cache
                                                            with conn:
                                                        sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 10276 and this is thread id 8364.`