Indicate a solution for unresolvable bits
When finding an unresolvable bit (X, Z, etc.), cocotb only displays an
error message, but does not indicate how to resolve the problem. Add
this piece of information.

Before:
ValueError: Unresolvable bit in binary string: 'z'

After:
ValueError: Unresolvable bit in binary string: 'z'. Set the
COCOTB_RESOLVE_X environment variable to configure how
special values are resolved.

(cherry picked from commit b2253f1dcc83771886261238648a2a102db9bbc8)