Fix compilation error on manylinux1
When compiling cocotb with "-Werror" on manylinux1 (Python 3.6/GCC 4.8.2) we get:

```
cocotb/share/lib/simulator/simulatormodule.cpp: In instantiation of ‘PyTypeObject {anonymous}::fill_common_slots() [with gpi_hdl = GpiCbHdl*; PyTypeObject = _typeobject]’:
  cocotb/share/lib/simulator/simulatormodule.cpp:1269:47:   required from here
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_object::ob_type’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘PyVarObject::ob_size’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_name’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_basicsize’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_itemsize’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_dealloc’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_print’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_getattr’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_setattr’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_as_async’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_repr’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_as_number’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_as_sequence’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_as_mapping’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_hash’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_call’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_str’ [-Werror=missing-field-initializers]
  cocotb/share/lib/simulator/simulatormodule.cpp:142:27: error: missing initializer for member ‘_typeobject::tp_getattro’ [-Werror=missing-field-initializers]
...
```