More helpful Python version check in setup.py
In setup.py we check if Python is sufficiently recent. For users running
the installation from Python 2 this can be a blocker to install (and
subsequently use) cocotb, we therefore need to invest into making it
easy for users to diagnose and fix the problem. In many cases Python 3
is available on a user's system, but not used, commonly due to the use
of 'pip' instead of 'pip3'. Explicitly add a hint in this regard and
point to the documentation for more details.

To make the error message even more friendly, remove the backtrace
generated as part of `RuntimeError()` and use `SystemExit()` instead.

On Ubuntu 18.04/2.7.17:

Before:

```
philipp@philipp-VirtualBox:~/src/cocotb$ pip install .
Processing /home/philipp/src/cocotb
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-kZcdoF-build/setup.py", line 33, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-kZcdoF-build/
```

after:

```
philipp@philipp-VirtualBox:~/src/cocotb$ pip install .
Processing /home/philipp/src/cocotb
    Complete output from command python setup.py egg_info:
    This version of cocotb requires at least Python 3.5,
    you are running Python 2.7.17.
    If you have Python 3 installed on your machine try
    using 'python3 -m pip' instead of 'pip' to install cocotb.
    For more information please refer to the documentation at
    https://cocotb.readthedocs.io.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-_N_j3r-build/
```